Частичное изменение классов, подключение базы данных mySQL
kapcap96/simple-accounting-app pull request #1
Opened 2021-11-05 16:40 UTC by kapcap96

### Основные изменения
- Частично изменены основные классы
- Добавлены аннотации Spring boot
- Изменен файл **aplication.properties** для подключения к локальному серверу базы данных MySQL
 `spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver`

- под каждый класс выделен специальный пакет

2021-11-06 09:44 UTC, Le0nX requested changes

2021-11-06 09:44 UTC, Le0nX commented on src/main/java/com/example/rest_example/controller/ClientControl.java
> +public class ClientControl {
Точно ли класс и файл должны так называться? `ClientControl` выглядит странно. Думаю, подразумевалось `ClientController` и `ClientController.java`?

2021-11-06 09:44 UTC, Le0nX commented on src/main/java/com/example/rest_example/service/ClientService.java
> -package com.example.rest_example.service;
`ClientService.java` и `ClientServiceImpl.java` точно должны быть удалены?

2021-11-07 09:43 UTC, Le0nX requested changes

2021-11-07 09:43 UTC, Le0nX commented on src/main/java/com/example/rest_example/controller/ClientControl.java
> +    @GetMapping(path = "/all_clients")
здесь лучше пропустить строку или 2, чтобы было понятно, что тут 2 метода, а не один

2021-11-07 18:27 UTC, MamaLemon commented on src/main/java/com/example/rest_example/controller/ClientControl.java
> +@RequestMapping (path = "/") //сопоставление HTTP-запроса с методом с использованием некоторых основных критериев.
Данную аннотацию необязательно использовать, так как у контроллера по дефолту 'path = "/"'

2021-11-07 18:27 UTC, MamaLemon commented on src/main/java/com/example/rest_example/controller/ClientControl.java
> +    private RepositoryClients repositoryClients;
Инжектить зависимости напрямую в поля компонента считается не самой лучшей затеей.
Наиболее правильный вариант - инжектить с помощью конструктора или сеттера.
Более подробную информацию можно прочитать [здесь](https://stackoverflow.com/questions/39890849/what-exactly-is-field-injection-and-how-to-avoid-it).

2021-11-07 18:27 UTC, MamaLemon commented on src/main/java/com/example/rest_example/controller/ClientControl.java
> +    @ResponseBody                                               //@ResponseBody  аннотация говорит контроллер, возвращаемый объект автоматически сериализуются в JSON и передается обратно в HttpRespon
Если все методы контроллера возвращают какие-то данные, то можно оптимизировать код, добавив в объявление контроллера аннотацию '@RestController' (вроде раньше у тебя так и было)

2021-11-07 18:27 UTC, MamaLemon commented on src/main/java/com/example/rest_example/repository/RepositoryClients.java
> +public interface RepositoryClients extends CrudRepository<Client,Integer> {
Нейминг класса можно улучшить, изменив порядок - `ClientsRepository`.
Это дело вкусовщины, каждому свое. Но как по мне, такое название более привычнее, поэтому и код читается легче

2021-11-07 18:27 UTC, MamaLemon commented on src/main/java/com/example/rest_example/model/Client.java
> +public class Client {
Первый момент: по-хорошему лучше не использовать модель дата слоя, как тело запроса, которое ты обрабатываешь в контроллере. Для таких дел пишут отдельные объекты (их еще называют DTO), которые включают все необходимые данные + поля этого объекта можно гибко настроить (название, формат данных, обязательное-необязательное).

Второй момент: есть такая замечательная либа - Lombok. С помощью нее ты сможешь заменить бойлерплейт код (геттеры, сеттеры, конструкторы) на аннотации, которые все за тебя сгенерят.

Третий момент: разве для JPA моделей не строго обязательно иметь конструктор без аргументов (это кстати тоже делается с помощью одной аннотации Lombok)

2021-11-08 14:14 UTC, Le0nX commented on src/main/java/com/example/rest_example/model/Client.java
> +public class Client {
Подробнее по первому моменту: https://www.baeldung.com/spring-boot-clean-architecture

Андрей имеет в виду архитектурную составляющую проекта. Помимо того, что нужно уметь правильно пользоваться библиотеками(spring/core/etc), одним из наиболее ценных в программировании считается навык правильного структурирования кода в проекте. Особенно это касается крупных проектов. Есть различные подходы к архитектурам, наиболее популярным и удобным счистится подход под названием Clean Architecture, основная суть которого сводится к разделению кода на различные слои. Можно дополнительно почитать про Clean Architecture применительно к java и spring boot в интернетах. Статей много, одну из них прикрепил выше.


Второй и третий момент - это уже задания со звездочкой для начинающего :)

2021-11-08 15:22 UTC, Le0nX commented on src/main/java/com/example/rest_example/model/Client.java
> +public class Client {
Нашел еще неплохую статью на русском, необязательно сейчас понимать ВСЕ-ВСЕ, но желательно просто знать, что этот вектор развития есть и что в какой-то момент за него надо будет взяться. Вначале хорошо просто знать, какие могут быть проблемы возникающие по мере роста сложности и размера проекта, и какие подходы способны эти проблемы исправить, чтобы потом более предметно погрузиться в эту тему. 

https://habr.com/ru/company/jugru/blog/419179/

2021-11-08 16:38 UTC, MamaLemon commented on src/main/java/com/example/rest_example/model/Client.java
> +public class Client {
По первому моменту тут даже имелись ввиду не проблемы архитектуры, а проблемы, которые могут возникнуть из-за использования jpa entity в качестве request/response body.
Сейчас это не вызывает проблем, а в будущем при проектировании БД появятся различные связи (@OneToMany, @OneToOne, @ManyToMany), и тогда ты сам себе выстрелишь в ногу. Имхо, баг искал целый день.
Вот [здесь](https://stackoverflow.com/questions/44872427/should-i-use-jpa-entity-in-rest-request-and-or-response) подробно описаны причины.

2022-08-09 12:28 UTC, merged